# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from getImageText import extractImageText

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(779, 547)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 100, 211, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fileLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fileLabel.setObjectName("fileLabel")
        self.verticalLayout.addWidget(self.fileLabel)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(370, 80, 371, 331))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(190, 440, 91, 41))
        self.runButton.setObjectName("runButton")
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(510, 440, 91, 41))
        self.resetButton.setObjectName("resetButton")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 20, 301, 41))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.themeLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.themeLabel.setObjectName("themeLabel")
        self.verticalLayout_3.addWidget(self.themeLabel)
        self.inputButton = QtWidgets.QPushButton(self.centralwidget)
        self.inputButton.setGeometry(QtCore.QRect(30, 190, 81, 31))
        self.inputButton.setObjectName("inputButton")
        self.clearFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearFileButton.setGeometry(QtCore.QRect(30, 260, 81, 31))
        self.clearFileButton.setObjectName("clearFileButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.clearFileButton.clicked.connect(self.fileLabel.clear) # type: ignore
        self.resetButton.clicked.connect(self.textEdit.clear) # type: ignore
        self.inputButton.clicked.connect(self.openFileDialog) # type: ignore
        self.runButton.clicked.connect(self.displayImageText) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Initialize the file path variable
        self.selectedFilePath = ""

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Text Extract"))
        self.fileLabel.setText(_translate("MainWindow", "图片放这里..."))
        self.runButton.setText(_translate("MainWindow", "运行"))
        self.resetButton.setText(_translate("MainWindow", "重置"))
        self.themeLabel.setText(_translate("MainWindow", "请传入你的图片(jpg、png)："))
        self.inputButton.setText(_translate("MainWindow", "放入"))
        self.clearFileButton.setText(_translate("MainWindow", "清空"))

    def openFileDialog(self):
        options = QFileDialog.Options()
        options |= QFileDialog.ReadOnly
        filePath, _ = QFileDialog.getOpenFileName(None, "选择图片文件", "", "图片文件 (*.jpg *.jpeg *.png);;所有文件 (*)", options=options)
        if filePath:
            self.selectedFilePath = filePath
            self.fileLabel.setText(filePath)

    def displayImageText(self):
        filePath = self.selectedFilePath.replace("\\", "/")
        # 先对图像进行retinex处理
        imageText = extractImageText(filePath)
        self.textEdit.setText(imageText)
